### ISSUE TITLE
Why return `reset` when the only one prop changed.

### ISSUE THREAD

**Issue by sky0014** [Two-Screen/symmetry#11]
```js
var symmetry = require("symmetry")

var a = {a: 1};
var b = {a: 2};
var patch = symmetry.createPatch(a,b);
```

This returns 'reset'. Is 'reset' means that two object can't be merged? Maybe it's better to return a real patch.

**Comment by sky0014** [comment]
My usage is that transfer a object change to prop change: 
```
var a = {a: 1};
a = {a: 2}; // --> a.a = 2;
```

So if this returns 'reset', It can't be performmed rightly, thanks~

**Comment by stephank** [comment]
This was discussed in #8, but never really happened. I just did an implementation of this, and tests pass, but I've not upgraded any of my own projects yet.

If you want to try it out, I created a prerelease [0.7.0-beta.1](https://github.com/Two-Screen/symmetry/releases/tag/v0.7.0-beta.1), which you can also install via tag `beta` using something like: `npm i symmetry@beta`

**Comment by sky0014** [comment]
Thanks! @stephank 
BTW: I saw that 0.7.0 has many changes, is it all for this or have other improvement like performance improve or bugfix?

**Comment by stephank** [comment]
It's only this change. It's not a big change in logic, but does change types that are used everywhere.

I didn't benchmark the changes yet.

**Comment by sky0014** [comment]
Ok, I got it, Thanks again for the work 😃
