### ISSUE TITLE
What does t: "o" mean?

### ISSUE THREAD

**Issue by LifeIsStrange** [Two-Screen/symmetry#5]
The patch metadata syntax should be documented plz
Also clarify wether deep patch avoid copying the values and do by reference

**Comment by stephank** [comment]
Sorry, did not yet have a need for this myself so far, but I can add a short section to the readme soon.

**Comment by stephank** [comment]
Sorry for the delay. I added a section to the README now. 🙂

**Comment by LifeIsStrange** [comment]
Thank u
