### ISSUE TITLE
Why not patched on the original object or give an option

### ISSUE THREAD

**Issue by sky0014** [Two-Screen/symmetry#9]
https://github.com/Two-Screen/symmetry/blob/ef72e5e9a577c69023544c8f9ea7874daff29969/src/patch.ts#L30

I'm trying to use this library with immer, but it always returned a cloned object, so that immer won't work.

Can it patch on the original object? Thx for the great work.

**Comment by stephank** [comment]
We had a similar use for preserving objects in the past, but no longer needed it ourselves. So when I moved this to TypeScript, I dropped it to save hassle in the migration.

It wasn't difficult to add back, though, so I've created a 0.6.1. In that version, there is a `applyPatch.inPlace()` that should do what you want. 🙂

**Comment by sky0014** [comment]
Nice job! 😄
